The salt.crypt module has more than one place where sys.exit() can be invoked.  I've run into an issue where instantiating a salt.client.Caller winds up triggering that, which is problematic given that salt.client is being used as a library.  Some sort of exception should be raised by salt.crypt instead.  
