**Description**
in 3004rc1, exiting running commands don't give the job's jid, I see this:
```
[root@ip-10-27-21-162 ~]# salt \* test.sleep 30
^C[ERROR   ] An un-handled exception was caught by salt's global exception handler:
TimeoutError: Operation timed out after None seconds
Traceback (most recent call last):
  File "/bin/salt", line 11, in <module>
    sys.exit(salt_main())
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 535, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 200, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 841, in cmd_cli
    **kwargs
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 1657, in get_cli_event_returns
    **kwargs
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 1192, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 1113, in get_returns_no_block
    auto_reconnect=self.auto_reconnect,
  File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 667, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 568, in _get_event
    raw = self.subscriber.read(timeout=wait)
  File "/usr/lib/python3.6/site-packages/salt/utils/asynchronous.py", line 125, in wrap
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/lib/python3.6/site-packages/salt/utils/asynchronous.py", line 131, in _target
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 458, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
salt.ext.tornado.ioloop.TimeoutError: Operation timed out after None seconds
Traceback (most recent call last):
  File "/bin/salt", line 11, in <module>
    sys.exit(salt_main())
  File "/usr/lib/python3.6/site-packages/salt/scripts.py", line 535, in salt_main
    client.run()
  File "/usr/lib/python3.6/site-packages/salt/cli/salt.py", line 200, in run
    for full_ret in cmd_func(**kwargs):
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 841, in cmd_cli
    **kwargs
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 1657, in get_cli_event_returns
    **kwargs
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 1192, in get_iter_returns
    for raw in ret_iter:
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 1113, in get_returns_no_block
    auto_reconnect=self.auto_reconnect,
  File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 667, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 568, in _get_event
    raw = self.subscriber.read(timeout=wait)
  File "/usr/lib/python3.6/site-packages/salt/utils/asynchronous.py", line 125, in wrap
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/lib/python3.6/site-packages/salt/utils/asynchronous.py", line 131, in _target
    result = io_loop.run_sync(lambda: getattr(self.obj, key)(*args, **kwargs))
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 458, in run_sync
    raise TimeoutError('Operation timed out after %s seconds' % timeout)
salt.ext.tornado.ioloop.TimeoutError: Operation timed out after None seconds
Exception ignored in: <generator object _read at 0x7f3fc4b17150>
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/transport/ipc.py", line 702, in _read
TypeError: catching classes that do not inherit from BaseException is not allowed
[root@ip-10-27-21-162 ~]# 

```

**Setup**
Install 3004rc1, I did with the bootstrap script.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [X] VM running on a cloud service, please be explicit and add details
Redhat 8 machine in aws.
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Install 3004rc1, run for example `salt \* test.sleep 30`, wait a few seconds and hit CTRL+C to exit.

**Expected behavior**
Expecting to see this as I do on 3003.3.
```
[root@ip-10-27-24-236 ~]# salt \* test.sleep 30
^C
Exiting gracefully on Ctrl-c
This job's jid is: 20210927201328118760
The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

salt-run jobs.lookup_jid 20210927201328118760

```

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004rc1
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.10.4
        pygit2: Not Installed
        Python: 3.6.8 (default, Jun 12 2019, 01:12:31)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: rhel 8.0 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-80.11.2.el8_0.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.0 Ootpa

```
</details>

**Additional context**
Add any other context about the problem here.
